import { v4 as uuidv4 } from "uuid";

export const projectList = [
  {
    id: uuidv4(),
    title: "Financial Control",
    projectInfo:
      "Aplicação para controle financeiro, com o Financial control você poderá adicionar e remover transações que foram feitas, podendo visualizar o total de entrada, saida e o saldo",
    tech: ["javascript, css, react, html"],
    image: "./imgs/project-imgs/financial-control.png",
    siteLink: "https://financial-control-flavioporfirio86.netlify.app/",
    repositoryLink: "https://github.com/flavioporfirio/financial-control",
    youtubeLink: "https://www.youtube.com/channel/UC6ewHz-YN0KpRCWoAH-sdMA",
    react: true,
    js: true,
    ts: false,
    html: true,
    css: true,
  },
  {
    id: uuidv4(),
    title: "Expert Notes",
    projectInfo:
      "Este projeto é uma aplicação web feita durante o evento da NLW - Expert na trilha de ReactJS. O usuário através da aplicação poderá criar notas de texto digitando ou por meio de audios, com a speechRecognition API nativa do próprio navegador.",
    tech: ["typescript, css, react, html"],
    image: "./imgs/project-imgs/expert-notes.png",
    siteLink: "https://expert-notes-flavio.netlify.app",
    repositoryLink: "https://github.com/flavioporfirio/nlw-expert-notes",
    youtubeLink: "https://www.youtube.com/channel/UC6ewHz-YN0KpRCWoAH-sdMA",
    react: true,
    js: false,
    ts: true,
    html: true,
    css: true,
  },
  {
    id: uuidv4(),
    title: "Apeperia",
    projectInfo: "SPA de uma empresa fictícia Apeperia",
    tech: ["javascript, css, react, html"],
    image: "./imgs/project-imgs/apeperia.png",
    siteLink: "https://apeperia-flavioporfirio86.netlify.app",
    repositoryLink: "https://github.com/flavioporfirio/apaperia/tree/master",
    youtubeLink: "https://www.youtube.com/channel/UC6ewHz-YN0KpRCWoAH-sdMA",
    react: false,
    js: true,
    html: true,
    css: true,
  },
];
