import { v4 as uuidv4 } from "uuid";

export const projectList = [
  {
    id: uuidv4(),
    title: "Financial Control",
    projectInfo:
      "Aplicação para controle financeiro, com o Financial control você poderá adicionar e remover transações que foram feitas, podendo visualizar o total de entrada, saida e o saldo",
    tech: ["javascript, css, react, html"],
    image: "./imgs/project-imgs/financial-control.png",
    siteLink: "https://financial-control-flavioporfirio86.netlify.app/",
    repositoryLink: "https://github.com/flavioporfirio/financial-control",
    youtubeLink: "",
    react: true,
    js: true,
    ts: false,
    html: true,
    css: true,
  },
  {
    id: uuidv4(),
    title: "Expert Notes",
    projectInfo:
      "Este projeto é uma aplicação web feita durante o evento da NLW - Expert na trilha de ReactJS. O usuário através da aplicação poderá criar notas de texto digitando ou por meio de audios, com a speechRecognition API nativa do próprio navegador.",
    tech: ["typescript, css, react, html"],
    image: "./imgs/project-imgs/expert-notes.png",
    siteLink: "https://expert-notes-flavio.netlify.app",
    repositoryLink: "https://github.com/flavioporfirio/nlw-expert-notes",
    youtubeLink: "",
    react: true,
    js: false,
    ts: true,
    html: true,
    css: true,
  },
  {
    id: uuidv4(),
    title: "Apeperia",
    projectInfo: "SPA de uma empresa fictícia Apeperia",
    tech: ["javascript, css, html"],
    image: "./imgs/project-imgs/apeperia.png",
    siteLink: "https://apeperia-flavioporfirio86.netlify.app",
    repositoryLink: "https://github.com/flavioporfirio/apaperia/tree/master",
    youtubeLink: "",
    react: false,
    js: true,
    html: true,
    css: true,
  },
  {
    id: uuidv4(),
    title: "E-commerce product page",
    projectInfo:
      "Solução para o E-commercer product page challenge on Frontend Mentor",
    tech: ["javascript, css, html"],
    image: "./imgs/project-imgs/ecommerce-product-page-main.png",
    siteLink:
      "https://flavioporfirio.github.io/frontend-mentor/ecommerce-product-page-main/",
    repositoryLink:
      "https://github.com/flavioporfirio/frontend-mentor/tree/main/ecommerce-product-page-main#links",
    youtubeLink: "",
    react: false,
    js: true,
    html: true,
    css: true,
  },
  {
    id: uuidv4(),
    title: "Dictionary web app",
    projectInfo:
      "Solução para o E-commercer product page challenge on Frontend Mentor",
    tech: ["javascript, css, html"],
    image: "./imgs/project-imgs/dictionary.png",
    siteLink: "https://dictionary-flavioporfirio86.netlify.app",
    repositoryLink: "https://github.com/flavioporfirio/dicitionary-web-app",
    youtubeLink: "",
    react: false,
    js: true,
    html: true,
    css: true,
  },
];
